### ISSUE TITLE
Problems with commas and functions of two variables

### ISSUE THREAD

**Issue by nielsle** [Eduap-com/WordMat#4] opened 2020-03-08 08:25 UTC
Hi Michael

I have some problems with using comma as argument separator when calculating partial derivatives of functions of two variables in wordmat. Here is an example
~~~
f(x,y):=x^2+y^2
f_x'(x, y) = 2*x
f_x'(2, 3) = 4,6   // I had expected either 2*2=4 or an error
~~~ 
Attached example file in Danish 
[funktioner_af_to_variable_i_wordmat.docx](https://github.com/Eduap-com/WordMat/files/4302991/funktioner_af_to_variable_i_wordmat.docx)

Kind regards  
      Niels

**Comment by Eduap-com** [comment] 2020-03-08 09:07
Thank you. I will have a look at it.

**Comment by Eduap-com** [comment] 2020-03-08 10:06
The problem is that WordMat sees 2,3 as the number 2,3 and not two different numbers 2 and 3. Hence x=2,3.
This can be resolved by putting a space after the comma 2, 3 (as you do in the text above, but not in the Word document) as WordMat then recognized this as two numbers and internally replaces , y ;
Thanks for attaching the docx file making it easy to resolve.
I can see that this could potentially throw students off, and it would be better with an error, but I am not sure how to change this as it depends on Maxima behavior.

**Closed by Eduap-com** 2020-03-08 10:06 UTC

**Comment by nielsle** [comment] 2020-03-08 12:15
Thank you for the quick response. I was mostly worried about the following line
~~~
f(x, y) =x^2+y^2
f_x'(2, 3) =4,6   // because 2*2.3=4.6
~~~
As I see it `f_x'(x,y)` is  function of two variables, so if wordmat interprets 2,3 as a Danish decimal number, then I would prefer wordmat to fail with a warning saying
~~~
Too few arguments
~~~
